[build]
  command  = "npm run build"

# REACT ROUTER
[[redirects]]
  from = "/*"
  to = "/"
  status = 200


  [[redirects]]
  from = "/api/*"
  to = "https://biology-server.herokuapp.com/:splat"
  status = 200