[build]
  command  = "npm run build"
# PROXY
[[redirects]]
  from = "/*"
  to = "https://xenodochial-gates-876873.netlify.app/.netlify/functions/:splat"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

