[build]
  command  = "npm run build"
# PROXY
[[redirects]]
  from = "/api/*"
  to = "https://xenodochial-gates-876873.netlify.app/.netlify/functions/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

# REACT ROUTER
[[redirects]]
  from = "/*"
  to = "/"
  status = 200